"""Regenerate embedded status icons with librsvg's rsvg-convert."""

import base64
import json
from pathlib import Path
import re
import subprocess

root = Path(__file__).resolve().parents[1]
icons = {}
for theme in ("dark", "light"):
    original = (root / f"site/assets/cache-tax-{theme}.svg").read_text()
    brand = "#d97757" if theme == "dark" else "#c15f3c"
    # Dark lids sit at 3:1 or better against both the light outline and the dark host backgrounds.
    colors = {"warm": "#669c4c" if theme == "dark" else "#397527",
              "cold": "#ce7153" if theme == "dark" else brand, "neutral": "#8b8b84" if theme == "dark" else "#686861"}
    icons[theme] = {}
    for state, color in colors.items():
        svg = original.replace(brand, color)
        # Three terminal columns are roughly 1.5 times as wide as one row is tall.
        terminal = svg.replace('width="64"', 'width="96"').replace('viewBox="0 0 64 64"', 'viewBox="-16 0 96 64"')
        # Claude's theme can differ from the terminal background. Edge both sides.
        group = re.search(r"<g .*?</g>", terminal, re.S).group()
        contrast = "#141413" if theme == "dark" else "#faf9f5"
        edge = re.sub(r'stroke="[^"]+"', f'stroke="{contrast}"', group).replace('stroke-width="4"', 'stroke-width="8"')
        terminal = terminal.replace(group, edge + group)
        png = subprocess.run(["rsvg-convert"], input=terminal.encode(), capture_output=True, check=True).stdout
        icons[theme][state] = {"svg": svg, "png": base64.b64encode(png).decode()}

(root / "hooks/status-icons.ts").write_text(
    "// Generated by tools/generate-status-icons.py from the official SVG assets.\n"
    + "export const statusIcons = " + json.dumps(icons, indent=2) + " as const\n"
)
